name: Deployment Workflow
on: 
    push:
        branches: [sfarm-github-actions]
jobs:
    deploy:
        name: Build, Pack and Deploy to Servers
        runs-on: ubuntu-20.04
        env:
            DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/chain-backend
        steps:
            - name: Checkout Source Code
              uses: actions/checkout@v2
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v1              
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Extract Metadata for Docker
              id: meta
              uses: docker/metadata-action@v3
              with:
                images: ${{ env.DOCKER_IMAGE_NAME }}
                tags:  |
                    type=sha,format=short
            - name: Build and Publish Private Image to Docker Hub
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                context: .
                file: dockerfile
                push: true
                labels: ${{ steps.meta.outputs.labels }}
                tags: ${{ steps.meta.outputs.tags }}
                cache-from: type=gha
                cache-to: type=gha,mode=max
            - name: Trigger Deployment on Servers
              uses: kevin-leptons/ssh_action@v1
              env:
                DOCKER_IMAGE_VERSION: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
              with:
                host: ${{ secrets.DEPLOYMENT_HOST }}
                key: ${{ secrets.DEPLOYMENT_KEY }}
                command: lz_service up chain-backend ${{ env.DOCKER_IMAGE_VERSION }}
